config/routes.rb
Rails.application.routes.draw do

  resources :contents
  get 'users/index'
  get 'schools/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products, only: [:index, :show] do
    resources :orders, only: :create
  end

  resources :orders, only: [:index, :destroy] do
  	collection do
  		get 'clean'

  	end
  end

  resources :billings, only: [] do
    collection do
      get 'pre_pay'
    end
  end

  resources :billings, only: [] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'products#index'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :product
  has_one_attached :image
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :billing, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders
  has_many :contents
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable, omniauth_providers: [:facebook]

  has_many :orders
  has_many :products, through: :orders
  validates :email, uniqueness: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
  end
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController

  def pre_pay

    orders = current_user.orders.where(payed: false)
    total = orders.pluck("price * quantity").sum()
    items = orders.map do |order|
      item = {}
      item[:name] = order.product.name
      item[:sku] = order.id.to_s
      item[:price] = order.price.to_s
      item[:currency] = 'USD'
      item[:quantity] = order.quantity
      item
    end

    payment = PayPal::SDK::REST::Payment.new({
      intent: "sale",
        payer: {payment_method: "paypal" },
        redirect_urls: {return_url: "https://quiet-beyond-24696.herokuapp.com/billings/execute", cancel_url: "https://quiet-beyond-24696.herokuapp.com/" },
        transactions: [{
          item_list: {items: items},
          amount: {
            total: total.to_s,
            currency: "USD" },
            description: "Compra desde E-commerce Rails."}]
      })



    if payment.create
      redirect_url = payment.links.find{|v| v.method == "REDIRECT"}.href
      redirect_to redirect_url
    else
      render json: payment.error
    end
  end

  def execute
    paypal_payment = PayPal::SDK::REST::Payment.find(params[:paymentId])
    if paypal_payment.execute(payer_id: params[:PayerID])
      amount = paypal_payment.transactions.first.amount.total
      billing = Billing.create(
        user: current_user,
        code: paypal_payment.id,
        payment_method: 'paypal',
        amount: amount,
        currency: 'USD'
      )
      orders = current_user.orders.where(payed: false)
      orders.update_all(payed: true, billing_id: billing.id)
      redirect_to root_path, notice: "La compra se realizó con éxito!"
    else
      render plain: "No se puedo generar el cobro en PayPal."
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < InheritedResources::Base

  private

    def content_params
      params.require(:content).permit(:name, :description, :product_id, :image)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!



  def create
    p = Product.find(params[:product_id])
    o = Order.find_or_create_by(user: current_user, product: p, payed: false, price: p.price)
    o.quantity += 1

    if o.save
      redirect_to products_path, notice: "El producto ha sido agregado al carro."
    else
      redirect_to products_path, alert: "El producto NO ha sido agregado al carro"
    end
  end

  def clean
    @orders = Order.where(user: current_user, payed: false)
    @orders.destroy_all
    redirect_to orders_path, notice: 'El carro se ha vaciado.'
  end

  def index
    @orders = current_user.orders.where(payed: false)
    @total = @orders.pluck("price * quantity").sum()
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end








private
  def product_params
      params.require(:product).permit(:content, :title, :photo, :description, :image)
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      redirect_to root_path, notice: 'Error al iniciar sesión con Facebook.'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    @products = current_user.products
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/_form.html.erb
<%= form_with(model: content, local: true) do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<div class="basic-body">
  <div class= "basic-body__presentaation">
    <div class= "container">
      <div class="row justify-content-md-center">
        <div class="card mb-3">
          <div class="card-body">
            <% @contents.each do |content| %>
            <%= video_tag url_for(content.image), controls: true, class: 'card-img-top' if content.image.attached? %>
            <h5 class="card-title"><%= content.name %></h5>
            <p class="card-text"><%= content.description %>%></p>
            <%= link_to 'Back', root_path %>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<% if @content.image.attached? %>
  <%= video_tag @content.image, class: 'card-img-top' %>
<% end %>
<p>
  <strong>Name:</strong>
  <%= @content.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @content.description %>
</p>

<p>
  <strong>Product:</strong>
  <%= @content.product %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<div class="container" style="margin-top: 100px;">
  <% if @orders.count > 0 %>
    <table class="table">
    <thead>
      <tr>
        <th>Producto</th>
        <th>Valor</th>
        <th>Cantidad</th>
        <th>Subtotal</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td> <%= order.product.name %> </td>
          <td> <%= order.price %></td>
          <td> <%= order.quantity %> </td>
          <td> <%= order.price * order.quantity %></td>
          <td><%= link_to 'Destroy', order_path(order), method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-success' %></td>

        </tr>
      <% end %>
      <tr class="table-dark">
      <td></td>
      <td></td>
      <td><strong>Total de la compra:</strong></td>
      <td><strong><%= @total %></strong></td>
      </tr>
    </tbody>
  </table>

  <%= link_to 'Limpiar carro', clean_orders_path, class: 'btn btn-outline-danger'  %>
  <%= link_to 'Confirmar compra', pre_pay_billings_path, class: 'btn btn-success float-right' %>

  <% else %>
    <p>No tienes productos en tu carro de compra.</p>
  <% end %>

</div>

app/views/products/index.html.erb
<div class="jumbotron jumbotron-fluid" style="margin-top:60px;">
  <div class="container">
    <h1 class="display-4">KIKI es la comunidad</h1>
    <p class="lead">de las Ideas y el Emprendimiento </p>

  </div>
</div>


<div class="container">
  <div class="row">
    <% @products.each_slice(4) do |row| %>
      <% row.each do |product| %>
        <div class="col" style="margin-top: 100px;">
          <div class="card" style="max-width: 300px;">
            <%= image_tag product.image, class: 'card-img-top' if product.image.attached? %>
            <div class="card-body">
              <h5> <%=link_to product.name, product_path(product), method: :get %> </h5>
              <p> <%= product.price %> </p>
              <%= link_to "Agregar al carro", product_orders_path(product), class: 'btn', method: :post  %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="w-70" style="margin-top:20px;"> </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="basic-body">
  <div class= "basic-body__presentaation">
    <div class= "container">
      <div class="row justify-content-md-center">
        <div class="card mb-3">
          <% if @product.image.attached? %>
          <%= image_tag @product.image, class: 'card-img-top' %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= @product.name %></h5>
            <p class="card-text"><%= @product.description %></p>
            <%= link_to 'Back', root_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/schools/index.html.erb
<div class="jumbotron">
  <h1>KIKI es la comunidad </h1>
    <h1>de emprendedores</h1>
  <p class="lead">Aprende cómo darle vida a tus ideas y proyectos</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Comencémos</a>
</div>

app/views/users/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4 center"><%=current_user.name%></h1>
    <h3 class="lead">STUDENT</h3>
  </div>
</div>

<div class="tab">
  <button class="tablinks" onclick="openPanel(event, 'Cursos')">Mis Cursos</button>
  <button class="tablinks" onclick="openPanel(event, 'Certificaciones')">Certificaciones</button>
  <button class="tablinks" onclick="openPanel(event, 'Perfil')">Editar Perfil</button>
  <button class="tablinks" onclick="openPanel(event, 'Sesión')">Cerrar Sesión</button>
</div>

<div id="Cursos" class="tabcontent">
  <h3>Mis Cursos</h3>
  <%@products.each do |product|%>
  <ul><%=link_to product.name, contents_path%></ul>
  <%end%>
</div>

<div id="Certificaciones" class="tabcontent">
  <h3>Certificaciones</h3>
  <p>Paris is the capital of France.</p>
</div>

<div id="Editar" class="tabcontent">
  <h3>Editar Perfil</h3>
  <p>Tokyo is the capital of Japan.</p>
</div>