config/routes.rb
Rails.application.routes.draw do

  resources :contents
  get 'users/index'
  get 'schools/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products, only: [:index, :show] do
    resources :orders, only: :create
  end

  resources :orders, only: [:index, :destroy] do
  	collection do
  		get 'clean'

  	end
  end

  resources :billings, only: [] do
    collection do
      get 'pre_pay'
    end
  end

  resources :billings, only: [] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'products#index'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :product
  has_one_attached :image
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :billing, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders
  has_many :contents
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable, omniauth_providers: [:facebook]

  has_many :orders
  has_many :products, through: :orders
  validates :email, uniqueness: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end

end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController

  def pre_pay

    orders = current_user.orders.where(payed: false)
    total = orders.pluck("price * quantity").sum()
    items = orders.map do |order|
      item = {}
      item[:name] = order.product.name
      item[:sku] = order.id.to_s
      item[:price] = order.price.to_s
      item[:currency] = 'USD'
      item[:quantity] = order.quantity
      item
    end

    payment = PayPal::SDK::REST::Payment.new({
      intent: "sale",
        payer: {payment_method: "paypal" },
        redirect_urls: {return_url: "https://quiet-beyond-24696.herokuapp.com/billings/execute", cancel_url: "https://quiet-beyond-24696.herokuapp.com/" },
        transactions: [{
          item_list: {items: items},
          amount: {
            total: total.to_s,
            currency: "USD" },
            description: "Compra desde E-commerce Rails."}]
      })



    if payment.create
      redirect_url = payment.links.find{|v| v.method == "REDIRECT"}.href
      redirect_to redirect_url
    else
      render json: payment.error
    end
  end

  def execute
    paypal_payment = PayPal::SDK::REST::Payment.find(params[:paymentId])
    if paypal_payment.execute(payer_id: params[:PayerID])
      amount = paypal_payment.transactions.first.amount.total
      billing = Billing.create(
        user: current_user,
        code: paypal_payment.id,
        payment_method: 'paypal',
        amount: amount,
        currency: 'USD'
      )
      orders = current_user.orders.where(payed: false)
      orders.update_all(payed: true, billing_id: billing.id)
      redirect_to root_path, notice: "La compra se realizó con éxito!"
    else
      render plain: "No se puedo generar el cobro en PayPal."
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < InheritedResources::Base

  private

    def content_params
      params.require(:content).permit(:name, :description, :product_id, :image)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!



  def create
    p = Product.find(params[:product_id])
    o = Order.find_or_create_by(user: current_user, product: p, payed: false, price: p.price)
    o.quantity += 1

    if o.save
      redirect_to products_path, notice: "El producto ha sido agregado al carro."
    else
      redirect_to products_path, alert: "El producto NO ha sido agregado al carro"
    end
  end

  def clean
    @orders = Order.where(user: current_user, payed: false)
    @orders.destroy_all
    redirect_to orders_path, notice: 'El carro se ha vaciado.'
  end

  def index
    @orders = current_user.orders.where(payed: false)
    @total = @orders.pluck("price * quantity").sum()
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end








private
  def product_params
      params.require(:product).permit(:content, :title, :photo, :description, :image)
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    @products = current_user.products
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="margin-top: 40px">
<head>
  <meta charset="utf-8">
   <meta name="Kiki App" content="Comunidad de emprendedores">
   <meta name="keywords" content="HTML,CSS,XML,JavaScript,Ruby">
   <meta name="author" content="Daniela Ballesteros">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>KIKI APP</title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <%= favicon_link_tag asset_path('favicon-16x16.png') %>
</head>

<body>
  <%= render 'shared/navbar'%>

  <% if alert.present? %>
  <div class="alert alert-warning" role="alert">
    <%= alert %>
  </div>
  <% end %>

  <% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
  <% end %>

  <div class="main-content">
    <%= yield %>
  </div>

  <%= render 'shared/footer'%>
</body>
</html>

app/views/shared/_chart.html.erb
<h2>Por día</h2>
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
<% my_chart = Order.group_by_day(:created_at).count %>
<%= column_chart my_chart %>

<h2>Por mes</h2>
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
<% my_chart = Order.group_by_month(:created_at).count %>
<%= column_chart my_chart %>

<h2>Por año</h2>
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
<% my_chart = Order.group_by_year(:created_at).count %>
<%= column_chart my_chart %>

app/views/shared/_footer.html.erb
<div class="container footer">
  <footer class="pt-4 my-md-5 pt-md-5 text-align mb-5">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-muted">&copy; 2019</small>
      </div>
      <div class="col-4 col-md">        <h5>KIKI APP</h5>
        <ul class="list-unstyled text-small">
          <li><%= link_to 'Cursos', root_path, class:'nav-link1' %></li>
          <li><%= link_to 'Escuela', schools_index_path, class:'nav-link2' %></li>
        </ul>
      </div>
    </div>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top bg-light">
  <%= link_to image_tag("logo_kiki_m.png", alt: "logo")%>
  <a class="navbar-brand" href="<%= root_path %>" style="padding-left: 20px;">Emprende</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= orders_path %>">Mi carro <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <%= link_to 'Cursos', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Academia', schools_index_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">

        <% if !user_signed_in? %>
          <li class="nav-item">
          <%= link_to 'Iniciar sesión', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
          <%= link_to 'Registrarse',  new_user_registration_path, class: 'nav-link'%>
          </li>
        <% else %>
        <li class="nav-item">
          <%= link_to current_user.name,  users_index_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        <% end %>
        </li>

    </ul>
  </div>
</nav>